### ISSUE TITLE
Error in the log, refers to: "*** Error opening \"%s.sha1\"; can't verify %s" % (fn, key)

### ISSUE THREAD

**Issue by Hadenix** [TeamWin/Team-Win-Recovery-Project#1589]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [ ] I have read the FAQ (https://twrp.me/FAQ/)
- [ ] I have searched for my issue and it does not already exist

**Device codename**: A5_Pro
**TWRP version**: 3.4.0_9

#### WHAT IS THE EXPECTED RESULT?
I get this error and can't build a recovery

#### ADDITIONAL INFORMATION

```
[  9% 1357/14278] Generated: (/home/hadenix/twrp-9/out/target/product/A5_Pro/android-info.txt)
FAILED: /home/hadenix/twrp-9/out/target/product/A5_Pro/android-info.txt 
/bin/bash -c "(build/make/tools/check_radio_versions.py ) && (echo \"board=mt6763\" > /home/hadenix/twrp-9/out/target/product/A5_Pro/android-info.txt )"
  File "build/make/tools/check_radio_versions.py", line 56
    print "*** Error opening \"%s.sha1\"; can't verify %s" % (fn, key)
          ^
SyntaxError: invalid syntax

```

**Comment by NavlysChen** [comment]
Hey bro, do you solve this problem?

**Comment by SL-Pirate** [comment]
python problem
I'm also porting a rom but can't figure out how to fix
please tell us if you fix this

**Comment by sevenrock** [comment]
Try this patch: https://review.lineageos.org/c/LineageOS/android_build/+/2981/2/tools/check_radio_versions.py#59
This patch might also be needed: https://review.lineageos.org/c/LineageOS/android_build/+/2988

**Comment by rumplestilzken** [comment]
> Try this patch: https://review.lineageos.org/c/LineageOS/android_build/+/2981/2/tools/check_radio_versions.py#59 This patch might also be needed: https://review.lineageos.org/c/LineageOS/android_build/+/2988

These patches fixed the build on Linux Mint 20.3, Python 3.8.10
and running the latest version of twrp minimal. Both were required to get the build to a stable state. The first i applied fixed the check_radio_versions exception. The second was required to fix a "'dict' object has no attribute 'iteritems'" excpetion.

**Comment by rumplestilzken** [comment]
You cannot compile the entire source using python3, you need to update your symlink for python to python2 not 3. Otherwise you will run into issues with print statements.
