### ISSUE TITLE
the latest version cannot compile on cm10.1 

### ISSUE THREAD

**Issue by imwls** [TeamWin/Team-Win-Recovery-Project#233]
bootable/recovery/updater/install.c:32:28: fatal error: sys/capability.h: No such file or directory
compilation terminated.
